sudo: required
language: node_js
node_js:
    - "node"
before_install:
    - export SOURCE_DIR=$(pwd)
    - cd src/main/resources/public/assets
install: 
    - yarn
    - sudo apt install -y groovy
jobs:
    include:
        stage: ChattyWebclient
        script: 
            - yarn start
        stage: ChatyService
        script:
            - cd ${SOURCE_DIR}
            - ./gradlew build
